### ISSUE TITLE
Please add v7.0.18

### ISSUE THREAD

**Issue by eahrold** [facetec/cocoapods-specs#5]
I notice that newer versions are available from your dev site. https://dev.zoomlogin.com/zoomsdk/#/downloads. 
Can you update the PodSpec with the newer versions.

**Comment by VitaliyGozhenko** [comment]
Can you update Cocoapods specs when you are releasing new version? It wasn't updated for 6 month. A lot of people are using Cocoapods instead of direct framework integration
